### ISSUE TITLE
errors when running ros

### ISSUE THREAD

**Issue by netbug19** [hofbi/telecarla#67]
My environment setup is:
Ubuntu 20.04
ROS Noetic
Carla 0.9.15

When I try to [run](https://github.com/hofbi/telecarla/blob/master/telecarla/README.md#Run), I get this error: 

```
~$ roslaunch telecarla telecarla_single_local.launch
... logging to /home/cct/.ros/log/4e39a7b8-3b05-11ef-88ec-358d60f1bee8/roslaunch-CCT-Project-PC-107240.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://CCT-Project-PC:46767/

SUMMARY
========

PARAMETERS
 * /carla_ros_bridge/ego_vehicle_role_name: ["hero", "ego_veh...
 * /carla_ros_bridge/fixed_delta_seconds: 0.05
 * /carla_ros_bridge/host: localhost
 * /carla_ros_bridge/passive: False
 * /carla_ros_bridge/port: 2000
 * /carla_ros_bridge/register_all_sensors: True
 * /carla_ros_bridge/synchronous_mode: True
 * /carla_ros_bridge/synchronous_mode_wait_for_vehicle_control_command: False
 * /carla_ros_bridge/timeout: 2
 * /carla_ros_bridge/town: Town01
 * /carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102/objects_definition_file: /home/cct/catkin_...
 * /carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102/spawn_point_ego_vehicle: 
 * /carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102/spawn_sensors_only: False
 * /gui/telecarla_gui/camera/front: /carla/ego_vehicl...
 * /gui/telecarla_gui/camera/front_left: /carla/ego_vehicl...
 * /gui/telecarla_gui/camera/front_right: /carla/ego_vehicl...
 * /gui/telecarla_gui/camera/rear: /carla/ego_vehicl...
 * /gui/telecarla_gui/camera/rear_left: /carla/ego_vehicl...
 * /gui/telecarla_gui/camera/rear_right: /carla/ego_vehicl...
 * /gui/telecarla_gui/force_feedback: False
 * /gui/telecarla_gui/joy_axis/brake: 3
 * /gui/telecarla_gui/joy_axis/steering_wheel: 0
 * /gui/telecarla_gui/joy_axis/throttle: 2
 * /gui/telecarla_gui/joy_button/manual: 0
 * /gui/telecarla_gui/joy_button/monitoring: 2
 * /gui/telecarla_gui/joy_button/reverse: 4
 * /gui/telecarla_gui/role_name: ego_vehicle
 * /gui/telecarla_gui/sensor_definition_file_path: /home/cct/catkin_...
 * /gui/telecarla_gui/vehicle_status: /carla/ego_vehicl...
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /set_initial_pose_ego_vehicle/control_id: control
 * /set_initial_pose_ego_vehicle/role_name: ego_vehicle
 * /use_sim_time: True

NODES
  /
    carla_ros_bridge (carla_ros_bridge/bridge.py)
    carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102 (carla_spawn_objects/carla_spawn_objects.py)
    set_initial_pose_ego_vehicle (carla_spawn_objects/set_initial_pose.py)
  /gui/
    telecarla_gui (telecarla_gui/telecarla_gui_node)

auto-starting new master
process[master]: started with pid [107248]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4e39a7b8-3b05-11ef-88ec-358d60f1bee8
process[rosout-1]: started with pid [107258]
started core service [/rosout]
process[carla_ros_bridge-2]: started with pid [107265]
process[carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102-3]: started with pid [107266]
process[set_initial_pose_ego_vehicle-4]: started with pid [107267]
process[gui/telecarla_gui-5]: started with pid [107268]
/home/cct/catkin_ws_teleop/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/home/cct/catkin_ws_teleop/devel/lib/carla_spawn_objects/carla_spawn_objects.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/cct/catkin_ws_teleop/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 22, in <module>
    from transforms3d.euler import euler2quat
ModuleNotFoundError: No module named 'transforms3d'
[carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102-3] process has died [pid 107266, exit code 1, cmd /home/cct/catkin_ws_teleop/devel/lib/carla_spawn_objects/carla_spawn_objects.py __name:=carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102 __log:=/home/cct/.ros/log/4e39a7b8-3b05-11ef-88ec-358d60f1bee8/carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102-3.log].
log file: /home/cct/.ros/log/4e39a7b8-3b05-11ef-88ec-358d60f1bee8/carla_spawn_objects_CCT_Project_PC_107240_4267685947593974102-3*.log
[ INFO] [1720207945.264731930]: Keyboard control available
[ INFO] [1720207945.436289294]: Subscribed to image topic for camera camera/front: /carla/ego_vehicle/front/image
[INFO] [1720207945.440656, 0.000000]: Trying to connect to localhost:2000
/home/cct/catkin_ws_teleop/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:416: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) != LooseVersion(CarlaRosBridge.CARLA_VERSION):
[FATAL] [1720207945.443019, 0.000000]: CARLA python module version 0.9.13 required. Found: 0.9.15
[INFO] [1720207945.444094, 0.000000]: Shutting down...
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/home/cct/catkin_ws_teleop/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 349, in destroy
    self.shutdown.set()
AttributeError: 'CarlaRosBridge' object has no attribute 'shutdown'
================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has died [pid 107265, exit code 1, cmd /home/cct/catkin_ws_teleop/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/cct/.ros/log/4e39a7b8-3b05-11ef-88ec-358d60f1bee8/carla_ros_bridge-2.log].
log file: /home/cct/.ros/log/4e39a7b8-3b05-11ef-88ec-358d60f1bee8/carla_ros_bridge-2*.log
Initiating shutdown!
================================================================================
[gui/telecarla_gui-5] killing on exit
[set_initial_pose_ego_vehicle-4] killing on exit
[carla_ros_bridge-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```
I have already installed the 'transforms3d' package, not sure why I'm getting an error for that. 

Any help is appreciated

**Comment by hofbi** [comment]
The error is not related to Telecarla but the [Carla ROS bridge](https://github.com/carla-simulator/ros-bridge). I found https://github.com/carla-simulator/ros-bridge/issues/683 which see to be an related issue.

I see the latest commit on the carla ros bridge is 2 years ago, and their [latest release](https://github.com/carla-simulator/ros-bridge/releases/tag/0.9.12) supports Carla 0.9.12.

**Comment by netbug19** [comment]
thanks for your response. I installed and setup Carla 0.9.12 however, when I run carla ros-bridge it gave me the error:

```
[FATAL] [1720217238.427815, 0.000000]: CARLA python module version 0.9.13 required. Found: 0.9.12
```

I double checked the [Carla ROS bridge](https://github.com/carla-simulator/ros-bridge) docs and it seems that it requires Carla 0.9.13, which I have installed and it's [running](https://carla.readthedocs.io/projects/ros-bridge/en/latest/ros_installation_ros1/#b-using-the-source-repository) fine. However, when I run telecarla, the simulation is not crashing as the initial error, but I'm still getting the error below as well as a black screen for the Teleop GUI:

```
/home/cct/catkin_ws_teleop/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/home/cct/catkin_ws_teleop/devel/lib/carla_spawn_objects/carla_spawn_objects.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/cct/catkin_ws_teleop/src/ros-bridge/carla_spawn_objects/src/carla_spawn_objects/carla_spawn_objects.py", line 22, in <module>
    from transforms3d.euler import euler2quat
ModuleNotFoundError: No module named 'transforms3d'
[carla_spawn_objects_CCT_Project_PC_125300_5611288119230126193-3] process has died [pid 125326, exit code 1, cmd /home/cct/catkin_ws_teleop/devel/lib/carla_spawn_objects/carla_spawn_objects.py __name:=carla_spawn_objects_CCT_Project_PC_125300_5611288119230126193 __log:=/home/cct/.ros/log/286064c6-3b16-11ef-88ec-358d60f1bee8/carla_spawn_objects_CCT_Project_PC_125300_5611288119230126193-3.log].
log file: /home/cct/.ros/log/286064c6-3b16-11ef-88ec-358d60f1bee8/carla_spawn_objects_CCT_Project_PC_125300_5611288119230126193-3*.log
```

It seems it is the same error that the user of  the issue you tagged is facing, but I'm not sure how to go about to solving it.

**Comment by hofbi** [comment]
Maybe update the Ros bridge to commit https://github.com/carla-simulator/ros-bridge/commit/c9d0c26c8efe71e4f8ca9ac3cfb9f4c5aca64b7c. From #20 I found that this version should work with 0.9.12.

**Comment by netbug19** [comment]
thank you I will try this out. just to confirm, the current telecarla version only works with Carla 0.9.12 correct?

**Comment by netbug19** [comment]
I updated the carla ros bridge to the commit you tagged as well as downgraded Carla to 0.9.12. I can run **roslaunch carla_ros_bridge carla_ros_bridge.launch** with no errors
However, when I try to run **roslaunch telecarla telecarla_single_local.launch**, i get the error below:

![Screenshot from 2024-07-08 12-38-23](https://github.com/hofbi/telecarla/assets/174821913/861dc427-5299-485b-82df-47b114598111)

**Comment by netbug19** [comment]
I'm not sure if this was the reason, but when I upgraded Python to the version (3.8.10) in addition to carla 0.9.12, everything is working fine now. thanks for the help

**Comment by hofbi** [comment]
Yes, I think the python version matters as well. Ros is a bit picky about it's dependencies. Ros noetic on Ubuntu 20.04 expects python 3.8.

But great that you could make it work.
